name: Cargo Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bazel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Bazel Test
      run: cd tests && bazel test --cxxopt=-std=c++23 --host_cxxopt=-std=c++23 //...

  cargo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose